### hello world
GET http://host.docker.internal:3333

### list all assets
GET http://host.docker.internal:3333/assets

### create a new asset
POST http://host.docker.internal:3333/assets
Content-Type: application/json

{
  "id": "asset1",
  "symbol": "A1",
  "price": 100
}

### list all wallets
GET http://host.docker.internal:3333/wallets

### create a new asset
POST http://host.docker.internal:3333/wallets
Content-Type: application/json

{
  "id": "wallet1"
}

### list assets from wallet
GET http://host.docker.internal:3333/wallets/wallet1/assets

### create a new asset in a wallet
POST http://host.docker.internal:3333/wallets/wallet1/assets
Content-Type: application/json

{
  "asset_id": "asset1",
  "shares": 10
}
