version: "3"

services:
  app:
    build: .
    container_name: codeinvest-backend
    ports:
      - "3333:3333"
      - "5555:5555"
    volumes:
      - ./:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: bitnami/mongodb:5.0.17
    container_name: codeinvest-db
    restart: always
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ADVERTISED_HOSTNAME: host.docker.internal
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: codeinvest
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb_data:
    driver: local
